### PR TITLE
Updated

### PR DESCRIPTION
**Pull request by sukru-can1**
Added my new node called EU - Naughty-Turtle

### CODE REVIEW

**Review by brandonlehmann — CHANGES_REQUESTED** [review]
Must be in alphabetical order please.

**Comment by sukru-can1** [comment]
> Must be in alphabetical order please.

So Should I update its order?

**Comment by brandonlehmann** [comment]
> > Must be in alphabetical order please.
> 
> So Should I update its order?

Yes

**Comment by sukru-can1** [comment]
> > > Must be in alphabetical order please.
> > 
> > 
> > So Should I update its order?
> 
> Yes

created a new pull request

**Comment by brandonlehmann** [comment]
Dupe #271

**Pull request closed without merging**
