### PR TITLE
Add some nodes

### PR DESCRIPTION
**Pull request by tr1pp**
Hi,

Wanting to add my new nodes.

Cheers

### CODE REVIEW

**Comment by RocksteadyTC** [comment]
what the hell in gods name is going on in here

**Comment by tr1pp** [comment]
i realised if have a SSL node i can also have normal node

**Comment by tr1pp** [comment]
and i dont know github shit

**Comment by tr1pp** [comment]
trying to make your network stronger with more nodes bro

**Comment by brandonlehmann** [comment]
I’m not sure how I personally feel with people putting “A” in the front of the node names just to put them at the top of the list… and for gods sake… clean up the formatting.

**Pull request closed without merging**
