### PR TITLE
Add Pubnodes

### PR DESCRIPTION
**Pull request by hooftly**
http://trtl.pubnodes.com:11898

### CODE REVIEW

**Comment by andrewnk** [comment]
Please make sure your node is publicly accessible.

**Comment by hooftly** [comment]
is it not?

**Comment by old-greywolf** [comment]
i just connected to it with zedwallet-beta, and it is syncing now

**Comment by andrewnk** [comment]
It wasn't accessible before which is why the travis checks failed, but looks good now.

**Pull request merged**
