### PR TITLE
Adding Node Turtleland.fun

### PR DESCRIPTION
**Pull request by mrlahaye**
{
      "name": "SouthEast Asia - Turtleland.fun",
      "url": "turtleland.fun",
      "port": 11898,
      "ssl": false
    }

### CODE REVIEW

**Comment by brandonlehmann** [comment]
Would you be so kind as to insert this in alphabetical order?

**Comment by mrlahaye** [comment]
Using name field?

**Comment by brandonlehmann** [comment]
Yes please.

**Comment by RocksteadyTC** [comment]
fixed

**Pull request merged**
