### PR TITLE
Update turtlecoin-nodes.json

### PR DESCRIPTION
**Pull request by old-greywolf**
changed the value of ssl to true for greywolf Germany at turtlenode.co

### CODE REVIEW

**Comment by brandonlehmann** [comment]
You are aware that none of the standard wallets support SSL yet, right?

**Comment by old-greywolf** [comment]
oh, no, i was not.  i thought that field had to reflect if the site was https enabled, so i changed it.



Sent from my phone, please excuse any typo.


-------- Original message --------

**Comment by old-greywolf** [comment]
ok, so i will go and change it back to false



Sent from my phone, please excuse any typo.


-------- Original message --------

**Comment by zpalmtree** [comment]
You don't need to change the PR - Can just close it.

**Comment by old-greywolf** [comment]
submitted change in error, sorry.

**Pull request closed without merging**
