### PR TITLE
Added turtlecoin.i2r.tech public node config

### PR DESCRIPTION
**Pull request by foomip**

### CODE REVIEW

**Comment by brandonlehmann** [comment]
@foomip your latency is very high on that node. Just a heads up.

**Comment by foomip** [comment]
Thanks @brandonlehmann  - the server is located in Germany (not sure where you are located?) - in any case it could very well be because it is busy syncing with the network right now (about 16% done) and is keeping the cpu busy at 100%? I will let you know once the sync is complete.

**Comment by brandonlehmann** [comment]
Roger that. It’s probably the load. :)

**Comment by foomip** [comment]
@brandonlehmann do you know how much space the entire blockchain uses right now? Didn't seem to find any up-to-date info anywhere.

**Comment by brandonlehmann** [comment]
About 105gb right now.

**Comment by foomip** [comment]
Cool thanks for the info.

**Pull request merged**
