### PR TITLE
Update turtlecoin-nodes.json

### PR DESCRIPTION
**Pull request by rickmascar**
This node is located in South America, Brazil at province of São Paulo

### CODE REVIEW

**Review by brandonlehmann — APPROVED** [review]

**Comment by brandonlehmann** [comment]
This node failed CI/CD checks that verifies that the node is reachable from the Internet. Is the node currently online and synced 100%?

**Comment by rickmascar** [comment]
Yes, by the "status" command it shows 100% synced  and online.

**Comment by brandonlehmann** [comment]
http://mascarins.duckdns.org:11898/info is not accessible.

```
> mascarins.duckdns.org
Server:  one.one.one.one
Address:  1.1.1.1

Non-authoritative answer:
Name:    mascarins.duckdns.org
Address:  186.223.213.10
```

Do you have a firewall blocking RPC requests to the node on port 11898? Did you bind the RPC to `0.0.0.0`?

**Comment by rickmascar** [comment]
The node is ending syncing, 99.99%. Its online.

**Comment by brandonlehmann** [comment]
> The node is ending syncing, 99.99%. Its online.

Node is still unreachable. Please see previous note.

**Comment by rickmascar** [comment]
The node is ending syncing, 99.99%. Its online. Now its synced.

**Comment by brandonlehmann** [comment]
> The node is ending syncing, 99.99%. Its online. Now its synced.

Node is still unreachable, please see my previous message(s).

**Comment by rickmascar** [comment]
Node seems to be online. I was with trouble with my second router port forwarding. Should be fixed now.

**Pull request merged**
