### PR TITLE
turtlecoin-nodes.json

### PR DESCRIPTION
**Pull request by dias11**
A new Node at the end of the file. Please add it to the list.
Thanks 
Chris

### CODE REVIEW

**Comment by andrewnk** [comment]
Please place your node in alphabetical order by name.

**Comment by dias11** [comment]
Thanks
i love turtle
Chris
    Στις Τετάρτη, 5 Ιουνίου 2019, 2:15:13 μ.μ. EEST, ο χρήστης Andrew <notifications@github.com> έγραψε:  
 
 
Please place your node in alphabetical order by name.

**Comment by dias11** [comment]
Andrew sorry
I cant see my node to wallet list yet.
I am new to that sorry to bother you.

**Comment by brandonlehmann** [comment]
Duplicate

**Comment by dias11** [comment]
I am completely lost here Andrew. Could you pls instruct me ?

**Pull request closed without merging**
