### PR TITLE
New node

### PR DESCRIPTION
**Pull request by linuxxp**
Adding new public node.

### CODE REVIEW

**Comment by andrewnk** [comment]
I am unable to reach 173.212.233.210:11898. Please make sure your node is publicly accessible.

**Comment by linuxxp** [comment]
Hello

 

It should works. Please check again. 

 

Thank you!

**Comment by ExtraHash** [comment]
Looks up now

**Comment by andrewnk** [comment]
I still can't see it.

```
vagrant@ubuntu1804:/$ nc -zvw3 173.212.233.210 11898
nc: connect to 173.212.233.210 port 11898 (tcp) failed: Connection refused
```

@ExtraHash you were able to get to it?

**Comment by linuxxp** [comment]
My VPS provider has technical issues now. After a few hours will be ok. I will write to you when everything is ok. Is that ok for you?

 

Thank you!

**Comment by brandonlehmann** [comment]
Sounds good.

**Comment by andrewnk** [comment]
Looks good now.

**Comment by linuxxp** [comment]
Thank you!

**Pull request merged**
